### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by roncapat** [GabriellaPace/Path_Planning#2]
Ciao Gabriella,

magari tracciamo qua problemi/dubbi/migliorie.

Per ora ho poco tempo, ho aperto un file e ti lascio qualche commento iniziale "da programmatore".

### 1 - Perchè non usare std::min()?
https://github.com/GabriellaPace/Path_Planning/blob/2a11a7886d6d361ae09491dc6a4f1e6e7f150936/Path_Planning/Head.h#L15-L24

### 2 - ++i più efficiente di i++ (anche nelle righe successive)
https://github.com/GabriellaPace/Path_Planning/blob/2a11a7886d6d361ae09491dc6a4f1e6e7f150936/Path_Planning/Head.h#L44

**Comment by GabriellaPace** [comment]
1 - semplicemente perché nel futuro quella funzione prenderà due vettori e dovrà calcolare la reciproca dominanza, l'ho modificata per prevedere temporaneamente dei semplici float e senza porci troppa attenzione (la versione con i vettori è commentata più in basso)
