### ISSUE TITLE
static shared pointer

### ISSUE THREAD

**Issue by GabriellaPace** [GabriellaPace/Path_Planning#3]
Credevo di essere riuscita a far funzionare questi puntatori ma mi sbagliavo:
https://github.com/GabriellaPace/Path_Planning/blob/0bb59d55f2fdc77c2dc8dcf76e5ef5bf04cd9bf0/Path_Planning/ClassNode.h#L17-L18
https://github.com/GabriellaPace/Path_Planning/blob/0bb59d55f2fdc77c2dc8dcf76e5ef5bf04cd9bf0/Path_Planning/ClassNode.h#L45-L54

NodesVect:
https://github.com/GabriellaPace/Path_Planning/blob/0bb59d55f2fdc77c2dc8dcf76e5ef5bf04cd9bf0/Path_Planning/ClassNode.h#L14
https://github.com/GabriellaPace/Path_Planning/blob/0bb59d55f2fdc77c2dc8dcf76e5ef5bf04cd9bf0/Path_Planning/ClassNode.h#L65

Sembra che vengano aggiornati solo quando vengono "interpellati", cioè quando per esempio c'è un ciclo 
for (auto Nr : Node::NodesVect)
vengono modificati i valori in NodesVect ma non in ptrToStart

**Comment by roncapat** [comment]
Ciao, perchè fai `make_shared<...>(*this)`?
Mi confermi che con quella riga vuoi _allocare una copia dell'oggetto corrente_?

**Comment by roncapat** [comment]
Per intenderci... se devi costruire un nuovo `Node` basta fare `std::make_shared<Node>()`.

**Comment by GabriellaPace** [comment]
Vorrei allocare un puntatore all'oggetto corrente (che sto creando in quel momento), ma senza creare una copia dell'oggetto

**Comment by roncapat** [comment]
Se ti interessa avere il puntatore all'oggetto corrente, già esistente, allora non puoi usare gli shared_ptr... Se il tuo oggetto è stato allocato sullo stack o comunque da qualcun altro sulla Heap, nel momento in cui l'ultimo shared_ptr riferito a quel pointer viene distrutto, l'oggetto viene deallocato con conseguenze dannose a runtime.

**Comment by roncapat** [comment]
Quindi, in questo caso credo che la cosa migliore sia salvarsi il puntatore secco, ovvero Node*, e non usare gli smart pointers.

**Comment by GabriellaPace** [comment]
Eh infatti pensavo di tradurlo poi in weak_pointer per evitare il problema della distruzione, è sbagliato comunque? 
Con i puntatori classici avevo provato ma non sono riuscita a farli funzionare in nessun modo. Non ricordo esattamente che problemi creassero, ma se non sbaglio così facendo gli oggetti venivano sovrascritti con valori totalmente randomici ogni volta che provavo anche solo a leggerli. Sicuramente causato da qualche mio utilizzo improprio.

**Comment by roncapat** [comment]
Mmmm, i weak pointer si basano sull'esistenza pregressq di uno shared
pointer da poter reclamare. Quindi per come la vedo ora non vanno bene...

Tu il primo nodo lo allochi staticamente o dinamicamente? Tutti i nodi
vengono inseriti in un contenitore globale?



Il ven 13 mag 2022, 17:11 GabriellaPace ***@***.***> ha
scritto:

**Comment by GabriellaPace** [comment]
Sì l'idea era di inserire un puntatore per ognuno in un vettore (Node::NodesVect) -> potrei usare questi come puntatori shared?
Poi salvavo semplicemente un'altra coppia di puntatori a start e goal, ma posso trovare una soluzione diversa per questo (o usare un weak ?) 
Al momento vengono allocati staticamente, ma se non ho capito male per rendere automatica la creazione (per esempio fatta da una funzione, quindi senza specificare ogni volta il nome) devo per forza renderla dinamica.

**Comment by GabriellaPace** [comment]
Per ora (credo) di aver risolto creando ogni nuovo oggetto così 
https://github.com/GabriellaPace/Path_Planning/blob/b87d1b0f8d82ae9b4abd13883337c37f5093074a/Path_Planning/ReadMap.h#L21
e creando tutti gli altri puntatori che mi servono come weak pointers, così è solo `NodesVect` (variabile globale) ad avere la gestione della vita degli oggetti e non dovrebbero esserci copie (_giusto?_). 
Può essere una soluzione valida?

**Comment by roncapat** [comment]
Dovrebbe essere la strada giusta, confermo.
